export type BlogInline = string | { text: string; href: string };
export type BlogBlock =
  | { type: "h2" | "h3"; text: string }
  | { type: "p"; content: BlogInline[] };

export const blogContent: Record<string, BlogBlock[]> = {
  "why-ongoing-website-maintenance-matters": [
    { type: "h2", text: "Maintenance protects business continuity" },
    { type: "p", content: ["A business website is connected to hosting, a CMS, third-party services, forms, analytics, and security controls. Each part changes over time. Without active ownership, small compatibility issues accumulate until a routine update becomes an outage or a lead path stops working."] },
    { type: "p", content: ["Ongoing ", { text: "website maintenance", href: "/website-maintenance" }, " turns that uncertainty into a managed process. Updates are reviewed, critical journeys are checked, backups are verified, and emerging risks are recorded before they become urgent."] },
    { type: "h2", text: "What a practical maintenance cycle includes" },
    { type: "h3", text: "Updates, QA, and operational visibility" },
    { type: "p", content: ["A useful monthly cycle covers dependency and CMS updates, uptime and security checks, form testing, responsive QA, performance review, and a clear release record. The exact checklist should reflect the website’s role: an ecommerce store needs checkout coverage, while a B2B website may prioritize inquiry forms, CRM routing, and key service pages."] },
    { type: "p", content: ["Maintenance should also create visibility. Teams need to know what changed, what remains risky, and which improvements deserve priority. That record reduces repeated investigation and makes future development easier to estimate."] },
    { type: "h2", text: "The cost of waiting for failure" },
    { type: "p", content: ["Reactive support often looks cheaper because there is no monthly line item. In practice, emergency diagnosis, lost inquiries, rushed releases, and uncertain backups cost more than planned care. Failure also tends to arrive at the least convenient time: during a campaign, a sales push, or a platform update."] },
    { type: "p", content: ["The goal is not to eliminate every incident. It is to reduce preventable failures, shorten recovery time, and give the business a technical partner who already understands the system."] },
  ],
  "website-support-vs-one-time-development": [
    { type: "h2", text: "Start with the nature of the work" },
    { type: "p", content: ["One-time development is appropriate when the outcome is clearly bounded: a new integration, a defined feature, or a website build with an agreed acceptance point. The team can specify scope, delivery stages, testing, and handover before work begins."] },
    { type: "p", content: ["Ongoing support fits a different reality. Priorities change, content evolves, vendors release updates, and small improvements arrive continuously. A support relationship preserves context so every request does not begin with a new technical discovery phase."] },
    { type: "h2", text: "Compare ownership, not only price" },
    { type: "h3", text: "Who is responsible after release?" },
    { type: "p", content: ["A project quote usually covers a defined output. It does not automatically include monitoring, post-release adjustments, dependency updates, or future troubleshooting. Businesses should ask who owns the website after launch, how incidents are handled, and whether documentation and access are complete."] },
    { type: "p", content: ["A structured ", { text: "website support plan", href: "/website-maintenance" }, " can include a regular capacity allowance, maintenance checks, QA, and prioritization. This makes cost more predictable while keeping senior technical knowledge available."] },
    { type: "h2", text: "Use a hybrid model when the roadmap is mixed" },
    { type: "p", content: ["Many B2B websites need both models. A redesign or custom workflow can run as a project, followed by ongoing support for releases, measurement, and incremental improvements. Larger features can still be scoped separately when they exceed the support allowance."] },
    { type: "p", content: ["Choose based on frequency, uncertainty, and business impact. If requests are recurring and the website is operationally important, continuity is valuable. If the requirement is stable and handover is realistic, a focused project may be enough."] },
  ],
  "why-qa-matters-after-every-update": [
    { type: "h2", text: "A small change can affect the whole system" },
    { type: "p", content: ["Website updates rarely remain isolated. A CSS adjustment can hide a mobile control, a plugin update can change form validation, and a tracking change can duplicate conversions. The code diff may be small while the operational impact is large."] },
    { type: "p", content: ["Quality assurance checks the behavior users and business teams depend on, not only whether the edited section looks correct. That distinction is essential for websites connected to payments, CRM systems, analytics, or publishing workflows."] },
    { type: "h2", text: "Build a risk-based QA checklist" },
    { type: "h3", text: "Test critical journeys first" },
    { type: "p", content: ["Start with revenue and lead paths: navigation, forms, checkout, account access, search, and key calls to action. Then cover representative browsers and screen sizes, accessibility basics, error states, metadata, and analytics events. The checklist should expand when a release touches a sensitive integration."] },
    { type: "p", content: ["Good QA also checks the environment around the change. Confirm caching behavior, redirects, consent rules, email delivery, and third-party responses where relevant. A staging pass is useful, but production smoke testing is still necessary because infrastructure and configuration can differ."] },
    { type: "h2", text: "Make verification part of delivery" },
    { type: "p", content: ["QA works best when acceptance criteria are written before development. Developers know what must remain stable, reviewers have a shared definition of done, and releases produce evidence instead of assumptions."] },
    { type: "p", content: ["Dimaso includes release-aware QA within ", { text: "ongoing website maintenance", href: "/website-maintenance" }, " so routine changes receive proportionate checks and high-risk work receives deeper coverage."] },
  ],
  "technical-seo-for-long-term-growth": [
    { type: "h2", text: "Technical SEO creates a dependable foundation" },
    { type: "p", content: ["Search growth depends on useful content, but search engines must first discover, render, interpret, and index the right URLs. Technical SEO reduces friction in that process through clear architecture, consistent canonical signals, stable internal links, and controlled crawl paths."] },
    { type: "p", content: ["The objective is not a perfect audit score. It is a website where important pages are accessible, duplication is controlled, performance supports users, and future publishing does not create avoidable indexation problems."] },
    { type: "h2", text: "Prioritize issues by business impact" },
    { type: "h3", text: "Crawlability, indexation, and page experience" },
    { type: "p", content: ["Begin with robots directives, XML sitemaps, response codes, redirects, canonicals, and internal navigation. Then review rendering, structured data, mobile behavior, Core Web Vitals, image delivery, and template metadata. These controls should be tested on representative page types rather than only the homepage."] },
    { type: "p", content: ["Large lists of warnings need context. An orphaned commercial page matters more than a harmless parameter URL. A slow high-conversion template deserves attention before a minor optimization on an unused page. Prioritization connects technical findings to acquisition and revenue."] },
    { type: "h2", text: "Protect SEO through continuous development" },
    { type: "p", content: ["Technical SEO is not a one-off launch task. New templates, migrations, JavaScript features, and CMS changes can alter crawl behavior. Include SEO acceptance criteria in ", { text: "web development", href: "/web-development" }, " and verify important signals after every material release."] },
    { type: "p", content: ["A stable baseline also makes content work more effective. When indexing and templates are reliable, teams can focus on answering buyer questions and strengthening the pages that should rank."] },
  ],
  "what-to-check-before-redesigning": [
    { type: "h2", text: "Do not redesign without a baseline" },
    { type: "p", content: ["A redesign changes more than visual presentation. It can alter navigation, content hierarchy, conversion paths, analytics, page speed, and search visibility. Before creating new screens, document how the current website performs and which parts already support the business."] },
    { type: "p", content: ["Review analytics, search queries, lead quality, user feedback, support requests, and CMS limitations. This separates evidence from internal preference and gives the redesign a measurable purpose."] },
    { type: "h2", text: "Inventory content and technical dependencies" },
    { type: "h3", text: "Map URLs, integrations, and ownership" },
    { type: "p", content: ["Create an inventory of indexed URLs, important backlinks, top landing pages, forms, downloads, scripts, CRM connections, consent tools, and third-party services. Decide which content will be retained, consolidated, rewritten, or retired before templates are finalized."] },
    { type: "p", content: ["The technical review should include hosting, CMS workflows, redirects, structured data, accessibility issues, and performance constraints. Hidden dependencies discovered late tend to create compromises or launch risk."] },
    { type: "h2", text: "Define success before design begins" },
    { type: "p", content: ["Set practical outcomes such as clearer service discovery, higher-quality inquiries, easier publishing, faster mobile pages, or safer campaign launches. Each major design decision can then be evaluated against a business need."] },
    { type: "p", content: ["Dimaso approaches ", { text: "web design", href: "/web-design" }, " as a connected system of positioning, UX, visual direction, responsive behavior, and conversion paths—not as a cosmetic layer placed over unresolved content and technology."] },
  ],
  "how-to-prepare-a-website-rfp": [
    { type: "h2", text: "Give partners enough context to make decisions" },
    { type: "p", content: ["A useful website RFP explains the business problem before listing requested features. Describe what the website supports today, where it creates friction, who uses it, and what should be different after the engagement."] },
    { type: "p", content: ["Include the current URL, platform, known integrations, internal stakeholders, target markets, and any fixed constraints. Sharing uncertainty is also useful; a capable partner can help define the solution when the outcome is clearer than the implementation."] },
    { type: "h2", text: "Separate requirements from assumptions" },
    { type: "h3", text: "Scope, content, technology, and governance" },
    { type: "p", content: ["List required capabilities, content responsibilities, approval steps, accessibility or compliance needs, migration expectations, analytics, SEO requirements, and post-launch support. Mark items as essential, preferred, or open for recommendation so proposals can make tradeoffs visible."] },
    { type: "p", content: ["Provide a realistic budget range and target timeline. These are design constraints, not negotiation mistakes. They help partners recommend an appropriate platform, team shape, and delivery sequence instead of producing a generic response."] },
    { type: "h2", text: "Ask for an approach, not only a price" },
    { type: "p", content: ["Request relevant experience, proposed phases, team responsibilities, QA practices, change control, assumptions, and ongoing ownership. Comparable proposals should explain what is included, what depends on discovery, and how risk will be managed."] },
    { type: "p", content: ["When the brief is ready, ", { text: "send Dimaso your RFP", href: "/contact" }, ". We review project context directly and can shape the engagement around maintenance, development, design, or a combination of services."] },
  ],
  "website-migration-without-losing-seo-value": [
    { type: "h2", text: "Treat migration as a controlled release" },
    { type: "p", content: ["A website migration can change the domain, platform, URL structure, rendering model, or all four. Search risk comes from changing multiple signals without a complete map of what existed before. The safest process begins with a crawl and an evidence-based URL inventory."] },
    { type: "p", content: ["Record indexable URLs, canonical targets, status codes, internal links, organic landing pages, backlinks, metadata, structured data, and sitemap coverage. This baseline becomes the acceptance test for the new website."] },
    { type: "h2", text: "Map every valuable URL deliberately" },
    { type: "h3", text: "Redirects must preserve intent" },
    { type: "p", content: ["Where URLs change, create one-to-one 301 redirects to the closest equivalent content. Avoid sending every retired page to the homepage, chaining redirects, or relying on pattern rules without checking exceptions. Update internal links so users and crawlers reach final destinations directly."] },
    { type: "p", content: ["Keep canonical tags, robots rules, hreflang where used, structured data, and XML sitemaps aligned with the production host. Staging blocks must be removed carefully, while genuinely private or duplicate areas should remain controlled."] },
    { type: "h2", text: "Validate before and after launch" },
    { type: "p", content: ["Crawl the staging build, compare templates, test redirects, and verify analytics before release. After launch, monitor server errors, indexation, rankings, traffic, Core Web Vitals, and conversion paths. Keep the old inventory available for regression checks."] },
    { type: "p", content: ["Migration-aware ", { text: "web development", href: "/web-development" }, " connects engineering, content, QA, and technical SEO. That coordination protects existing value while allowing the platform to improve."] },
  ],
  "what-good-website-maintenance-reporting-looks-like": [
    { type: "h2", text: "A report should support decisions" },
    { type: "p", content: ["Maintenance reporting is not a list of technical activity. Business teams need to understand what changed, why it mattered, whether the website is healthy, and what should happen next. A long export of updates and uptime events does not provide that context."] },
    { type: "p", content: ["The report should be concise enough to review but specific enough to establish accountability. It becomes a shared operational record for the client and technical team."] },
    { type: "h2", text: "Cover work, health, risk, and outcomes" },
    { type: "h3", text: "Separate completed work from open decisions" },
    { type: "p", content: ["Summarize releases, updates, fixes, content support, and QA completed during the period. Add website health indicators relevant to the platform: uptime, backups, security findings, performance, form delivery, ecommerce checks, or analytics integrity."] },
    { type: "p", content: ["Open risks need an owner, impact statement, and recommendation. Distinguish urgent remediation from planned improvement and optional ideas. This prevents important technical debt from disappearing inside a general backlog."] },
    { type: "h2", text: "Connect reporting to the next cycle" },
    { type: "p", content: ["Useful reporting ends with priorities for the next period. Recommendations should reflect business events, available capacity, dependencies, and evidence—not a generic optimization checklist."] },
    { type: "p", content: ["Dimaso’s ", { text: "website maintenance service", href: "/website-maintenance" }, " combines practical care with clear visibility, so teams can see both the work completed and the decisions required to keep the platform reliable."] },
  ],
  "design-systems-for-growing-websites": [
    { type: "h2", text: "Growth exposes inconsistency" },
    { type: "p", content: ["A website can look coherent at launch and become fragmented after months of campaigns, service additions, and content updates. Teams recreate similar sections, spacing drifts, and new pages introduce one-off components because the original design did not define reusable rules."] },
    { type: "p", content: ["A practical design system gives designers, developers, and content editors a shared language. It protects quality while making routine expansion faster."] },
    { type: "h2", text: "Build from tokens to page patterns" },
    { type: "h3", text: "Document decisions at the right level" },
    { type: "p", content: ["Start with typography, color roles, spacing, grids, breakpoints, states, and accessibility requirements. Then define reusable interface elements and larger content patterns such as service introductions, proof sections, article cards, forms, and calls to action."] },
    { type: "p", content: ["Documentation should explain purpose and constraints, not only show a component. Editors need to know when a pattern is appropriate, developers need expected behavior, and designers need clear extension rules."] },
    { type: "h2", text: "Treat the system as a product" },
    { type: "p", content: ["A design system needs ownership. Review new patterns, remove duplication, test responsive and interactive states, and update documentation alongside releases. Governance can be lightweight, but it cannot be absent."] },
    { type: "p", content: ["Dimaso’s ", { text: "web design service", href: "/web-design" }, " connects visual direction with reusable UX structure and implementation reality, helping growing websites stay consistent without blocking useful change."] },
  ],
  "when-custom-web-development-is-worth-it": [
    { type: "h2", text: "Custom development should solve a real constraint" },
    { type: "p", content: ["Custom code is valuable when standard tools cannot represent the workflow, integration, performance target, or administrative experience the business needs. It is not automatically better than a proven platform feature, and unnecessary customization creates maintenance cost."] },
    { type: "p", content: ["The decision should begin with the operating model. Identify who uses the system, what data moves through it, where existing tools fail, and what the failure costs in time, revenue, or risk."] },
    { type: "h2", text: "Look for strong business signals" },
    { type: "h3", text: "Complex rules, integrations, and scale" },
    { type: "p", content: ["Custom development is often justified by pricing or account rules, specialized ecommerce behavior, CRM and ERP integrations, member portals, directories, booking logic, editorial workflows, or high-volume operations. It can also improve reliability when a chain of plugins has become difficult to test and support."] },
    { type: "p", content: ["Estimate the full lifecycle: discovery, implementation, migration, QA, documentation, hosting, monitoring, and future change. The right comparison is total operational value, not the initial cost of custom code versus a subscription."] },
    { type: "h2", text: "Use the smallest durable solution" },
    { type: "p", content: ["A strong technical approach may combine established services with a focused custom layer. This reduces reinvention while preserving the workflow that creates competitive value. Clear interfaces and documentation keep that layer maintainable."] },
    { type: "p", content: ["Dimaso provides ", { text: "custom web development", href: "/web-development" }, " for business rules, integrations, CMS workflows, and digital platforms where dependable behavior matters more than adding another generic feature."] },
  ],
};
