export type ServiceKey = "maintenance" | "development" | "design";

export const services = {
  maintenance: {
    slug: "website-maintenance",
    serviceType: "Website Maintenance and Support",
    label: "Web Maintenance",
    eyebrow: "Ongoing technical partnership",
    title: "Web maintenance services that keep your platform reliable.",
    intro: "Dimaso provides ongoing website care, WordPress maintenance, QA, security checks, performance monitoring, and fast technical support for teams that cannot afford platform drift.",
    keywords: ["Monthly support retainers", "Updates, fixes & QA", "Security & backups", "Performance monitoring", "WordPress care", "Fast technical response", "Technical SEO upkeep", "Analytics & reporting", "Integration support"],
    problems: ["Updates create unexpected regressions", "Small fixes sit in a backlog for weeks", "Security, backups, and performance are reactive", "No technical partner owns the full website picture"],
    process: ["Baseline audit", "Prioritized support plan", "Continuous delivery & QA", "Monthly reporting and roadmap"],
    subject: "New RFP Request - Website Maintenance - dimaso.co",
  },
  development: {
    slug: "web-development",
    serviceType: "Custom Web Development",
    label: "Web Development",
    eyebrow: "Custom engineering",
    title: "Web development services built around business-critical workflows.",
    intro: "From custom WordPress and CMS development to API integrations, payment workflows, and complex website features, Dimaso engineers reliable systems that fit the way your business operates.",
    keywords: ["Custom web development", "WordPress development", "API integrations", "Payment workflows", "CMS development", "Technical SEO implementation"],
    problems: ["Off-the-shelf tools do not fit the workflow", "Integrations fail or lose data", "Legacy code blocks product growth", "Performance and technical SEO limit acquisition"],
    process: ["Technical discovery", "Architecture & delivery plan", "Iterative development & QA", "Launch, documentation & support"],
    subject: "New RFP Request - Web Development - dimaso.co",
  },
  design: {
    slug: "web-design",
    serviceType: "Web Design and Website Redesign",
    label: "Web Design",
    eyebrow: "Clarity, conversion, systems",
    title: "Web design services for sharper positioning and better conversion.",
    intro: "Dimaso creates responsive website redesigns, landing pages, UX/UI improvements, and practical design systems that make complex businesses easier to understand and act on.",
    keywords: ["Website redesign", "UX/UI web design", "Responsive design", "Landing pages", "Conversion-focused layouts", "Design systems"],
    problems: ["The website no longer reflects the business", "Users struggle to understand the offer", "Campaign landing pages underperform", "Visual inconsistency slows the internal team"],
    process: ["Research & content structure", "UX direction", "Interface system & prototypes", "Responsive delivery & refinement"],
    subject: "New RFP Request - Web Design - dimaso.co",
  },
} as const;

export const homeFaq = [
  ["What kind of websites does Dimaso work on?", "Dimaso works on business websites, WordPress platforms, ecommerce experiences, landing pages, CMS-driven sites, and custom web systems that need reliable maintenance, development, design, QA, or technical support."],
  ["Can you support an existing website, or only build new ones?", "We can support, improve, or rebuild an existing website. Many engagements start with an audit, urgent fixes, or a maintenance backlog before moving into larger improvements."],
  ["Do you work with companies outside your country?", "Yes. Dimaso works with companies in the US, the EU, and other international markets, with clear communication, practical documentation, and flexible overlap for teams in different time zones."],
  ["How do you usually start a project?", "We start by understanding the platform, business goals, current risks, priorities, stakeholders, and timeline. From there we define a focused scope, delivery rhythm, and the first measurable outcomes."],
  ["Can Dimaso work with our internal marketing or product team?", "Yes. We often collaborate with internal marketing, product, design, and engineering teams. We keep responsibilities clear so your team always knows what is being worked on and why."],
  ["Do you handle both design and development?", "Yes. Dimaso can handle design, development, maintenance, QA, and technical implementation together, which helps keep decisions connected instead of split across disconnected vendors."],
  ["What makes Dimaso different from a typical agency?", "Dimaso is built around senior technical ownership, direct communication, ongoing care, and practical business context. The goal is not only to deliver tasks, but to keep the website dependable as the business changes."],
] as const;

export const serviceFaqs: Record<ServiceKey, readonly (readonly [string, string])[]> = {
  maintenance: [
    ["What is included in web maintenance?", "A maintenance engagement can include WordPress and plugin updates, backups, uptime checks, security review, performance monitoring, bug fixes, content support, QA, reporting, and prioritized technical improvements."],
    ["Do you test the website after updates?", "Yes. Updates are paired with QA across critical pages, forms, checkout flows, responsive layouts, and business-critical journeys so small technical changes do not quietly create regressions."],
    ["Can you take over a website that another team built?", "Yes. We can audit the current setup, document risks, review the codebase and hosting environment, then create a practical maintenance plan without needing to rebuild everything first."],
    ["How quickly can you respond to urgent issues?", "Response time depends on the engagement level, but maintenance clients get a clear support process for urgent fixes, production issues, broken forms, failed updates, and other website problems that affect the business."],
    ["Do you provide monthly reporting?", "Yes. We can provide monthly summaries covering completed work, open risks, performance notes, security or update status, recommendations, and next priorities for the website."],
    ["Is maintenance only for WordPress websites?", "WordPress maintenance is a common part of our work, but we can also support custom websites, CMS platforms, frontend applications, integrations, and technical workflows depending on the stack."],
    ["Can maintenance turn into ongoing improvements?", "Yes. Maintenance often creates the clearest path for continuous improvement because we see recurring issues, user friction, performance gaps, and technical debt before they become larger problems."],
    ["How does a website maintenance engagement begin?", "We begin with an access review and baseline audit covering the platform, hosting, backups, integrations, critical user journeys, known issues, and update risk. We then define priorities, response expectations, and a practical maintenance plan."],
    ["How is a maintenance plan priced?", "Pricing depends on the platform, business-critical functionality, response expectations, update frequency, and the amount of ongoing development or content support required. We define the scope after reviewing the current website and support needs."],
  ],
  development: [
    ["What type of web development does Dimaso handle?", "Dimaso handles custom website development, WordPress development, CMS builds, API integrations, payment workflows, technical SEO implementation, performance improvements, and business-specific website features."],
    ["Can you build custom functionality for an existing website?", "Yes. We can extend an existing website with custom features, integrations, workflows, content structures, automation, or frontend improvements while respecting the platform already in place."],
    ["Do you work with APIs and third-party systems?", "Yes. We build and stabilize integrations with CRMs, payment providers, ecommerce systems, marketing tools, analytics platforms, booking systems, and other operational software."],
    ["How do you keep development work reliable?", "We define the technical approach before building, work in controlled iterations, test critical flows, review edge cases, and document the implementation so the website can keep evolving after launch."],
    ["Can you improve website speed and technical SEO?", "Yes. Performance and technical SEO can be part of development work, including Core Web Vitals, crawlability, metadata, schema, redirects, image handling, frontend performance, and structural cleanup."],
    ["Do you provide documentation after development?", "Yes. For important features and workflows, we provide practical documentation so internal teams understand how the system works, what was changed, and how to manage it safely."],
    ["Can you support the website after launch?", "Yes. Development projects can move into maintenance or ongoing support so fixes, monitoring, QA, and future improvements stay with the team that understands the platform."],
    ["How long does a custom web development project take?", "Timing depends on discovery, integration complexity, content readiness, and QA requirements. A focused feature may take several weeks, while a larger platform or migration is planned in phases with clear release milestones."],
    ["Can your team work with our internal developers or marketing team?", "Yes. We can own a defined technical scope or work alongside internal development, product, marketing, and content teams with clear responsibilities, documentation, and release processes."],
  ],
  design: [
    ["What is included in web design services?", "A web design engagement can include website redesign, UX direction, responsive layouts, landing pages, content hierarchy, interface systems, conversion improvements, and design support for development."],
    ["Do you design with conversion in mind?", "Yes. Design decisions are connected to clarity, trust, user intent, calls to action, content flow, and the practical actions visitors need to take on the website."],
    ["Can you redesign only part of a website?", "Yes. We can redesign high-value pages, service pages, landing pages, navigation, forms, or specific user journeys without requiring a full website redesign from day one."],
    ["Do you handle responsive design for mobile and tablet?", "Yes. Responsive behavior is part of the design process, including layout, typography, spacing, navigation, forms, and content priority across desktop, tablet, and mobile."],
    ["Can you work with our existing brand?", "Yes. We can refine and extend an existing brand into a stronger web system, or create a more structured visual direction when the current website no longer reflects the business."],
    ["How do you make complex services easier to understand?", "We work on content structure, page hierarchy, interface patterns, visual rhythm, and clearer calls to action so visitors understand the offer faster and move through the site with less friction."],
    ["Can design be connected directly to development?", "Yes. Dimaso can connect design and development in one process, which helps prevent attractive concepts from becoming difficult, fragile, or inconsistent once implemented."],
    ["What do you need from our team before design starts?", "We need the business goals, priority audiences, current website context, available content and brand assets, relevant analytics, and the stakeholders responsible for feedback and approval."],
    ["How long does a website redesign usually take?", "Timing depends on the number of page templates, content readiness, stakeholder availability, and whether development is included. We define clear phases for structure, visual direction, responsive design, review, and implementation support."],
  ],
} as const;

export const caseStudies = [
  { slug:"forever-living-shop", name: "Forever Living Shop", category: "Development / Ecommerce", website:"https://foreverliving.com/", image: "/case-studies/forever-living-shop.jpg", imageAlt:"Forever Living ecommerce platform with member discount logic and WooCommerce development by Dimaso", summary: "A resilient ecommerce platform for Forever Living Serbia & Montenegro.", overview:"Forever Living Shop was not a simple product catalog. The platform had to support ecommerce, member logic, different customer types, internal administration, and a commercial model where discounts depend on who the user is and what kind of account they have. For a brand with a large active member base, the website needed to feel easy for shoppers while still respecting complex business rules behind the scenes.", problem: "The biggest challenge was aligning the shopping experience with different user groups and member statuses. More than 42,000 active members needed to be handled in a way that protected account logic, pricing visibility, discount percentages, and checkout reliability. At the same time, the catalog, URLs, content structure, and purchase paths had to stay stable so technical changes did not create confusion for users or damage SEO value.", solution: "Dimaso worked on the ecommerce structure, user-role logic, discount assignment, responsive purchase paths, and QA around the most sensitive flows. We treated the project as both development and long-term maintenance: preserve what already worked, improve what slowed the team down, and make the platform easier to extend. SEO-sensitive URLs and important product paths were reviewed so improvements could happen without casually breaking existing visibility.", workSummary:"We worked across ecommerce architecture, account segmentation, discount logic, product discovery, checkout clarity, responsive behavior, analytics readiness, technical SEO checks, and quality assurance for critical purchase paths. The goal was to make the shop feel simple on the surface while giving the business dependable control over complex member and customer rules.", work:["User roles and member discount logic","Ecommerce structure and checkout support","SEO-sensitive URL preservation","QA for critical purchase paths"], result: "The result is a more dependable ecommerce platform that can support everyday shoppers, registered members, and internal business rules without forcing the team into manual workarounds. The website is easier to maintain, clearer to use, and better prepared for future catalog, pricing, and operational changes.", services: "Development · Ecommerce · Maintenance", href: "/web-development", cta:"Related development service", serviceTags:["Web Development","Website Maintenance","Technical SEO","QA","Integrations"], technologies:["WordPress","WooCommerce","PHP","Member Logic","Technical SEO","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["42,000+","active member records supported"],["+18%","conversion flow clarity"],["+30%","faster key page load"]] },
  { slug:"doctor-medica", name: "Doctor Medica", category: "Web Design / Medical Website", website:"https://www.doctormedica.co/", image: "/case-studies/doctor-medica.jpg", imageAlt:"Doctor Medica healthcare website redesign with responsive medical service pages by Dimaso", summary: "A clean, reliable website presence for a medical-facing business.", overview:"Doctor Medica needed a website that could communicate medical trust without becoming cold or generic. Visitors needed to understand the offer, move through service information confidently, and feel that the business had a serious technical and visual foundation behind it.", problem: "The existing presentation needed sharper structure, clearer service hierarchy, and a calmer interface. Medical websites carry an extra layer of trust: typography, spacing, loading behavior, mobile layout, and content order all influence whether a visitor feels they are in the right place. The challenge was to improve clarity while keeping the experience restrained and professional.", solution: "Dimaso shaped the visual system, page hierarchy, responsive layouts, and service presentation around credibility. We supported the technical foundation with QA, metadata review, image handling, and technical SEO basics so the website could be both presentable and easier to maintain after launch.", workSummary:"The work focused on website design direction, service content hierarchy, responsive interface decisions, technical QA, metadata hygiene, and the visual discipline expected from a medical-facing brand. We kept the design measured so trust came from clarity, consistency, and reliable page behavior.", work:["Medical website design direction","Responsive development","Service content structure","Technical SEO and QA support"], result: "The website now presents the business with more confidence and less friction. Service paths are easier to scan, the interface feels more professional, and the technical structure gives the team a stronger base for ongoing updates and future content improvements.", services: "Design · Development · Medical Website", href: "/web-design", cta:"Related design service", serviceTags:["Web Design","Web Development","Technical SEO","QA"], technologies:["Responsive UI","Metadata","Image Optimization","Technical SEO","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+40%","clearer service discovery"],["+25%","stronger UX clarity"],["+30%","faster page load target"]] },
  { slug:"call-the-waiter", name:"Call the Waiter", category:"Development / Hospitality Application", website:"https://callthewaiter.rs/", image:"/case-studies/call-the-waiter.jpg", imageAlt:"Call the Waiter hospitality application website for restaurant and hotel staff communication by Dimaso", summary:"A digital product presence for hospitality teams that need faster guest and staff communication.", overview:"Call the Waiter is a product-led website for hospitality teams. The platform needed to explain a real operational workflow: guests call staff through the app, waiters and kitchen teams coordinate faster, and venues reduce friction in service communication. The website had to make that value understandable before a demo or sales conversation.", problem:"The product was useful, but the website needed to translate functionality into business meaning. Hotel and restaurant decision-makers do not only need features; they need to see how the system fits daily operations, staff response, guest expectations, and internal communication. The challenge was to make the product feel practical, not abstract.", solution:"Dimaso structured the digital presentation around hospitality workflows, product value, responsive layouts, and a clear path for interested venues to understand the platform. We kept the messaging focused on operational outcomes and made the website easier to extend as the product story evolves.", workSummary:"We translated product functionality into a clearer website narrative, organized workflow messaging, refined responsive presentation, improved the inquiry path, and supported QA around forms and key pages. This is the kind of work where development and product positioning meet: the website has to explain the software, not just display it.", work:["Product positioning","Hospitality workflow messaging","Responsive product website","Lead and inquiry path support"], result:"The product now has a clearer digital presence for hotels, restaurants, and service teams. Visitors can understand the use case faster, connect the app to real hospitality operations, and move toward inquiry with less explanation required from the sales team.", services:"Development · Product Website", href:"/web-development", cta:"Related development service", serviceTags:["Web Development","Web Design","QA"], technologies:["Product UX","Responsive UI","Forms","Content Structure","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+25%","clearer product messaging"],["+18%","lead flow improvement"],["+40%","support explanation clarity"]] },
  { slug:"one-llama-travels", name:"One Llama Travels", category:"Development / Travel Platform", website:"https://onellamatravels.com/", image:"/testimonials/one-llama-peru.jpg", imageAlt:"One Llama Travels Peru travel platform with booking integration and AI features developed by Dimaso", summary:"A travel platform implementation with booking system integration and AI-based functionality.", overview:"One Llama Travels needed a website foundation that could support destination content, travel presentation, booking-related workflows, and a more advanced technical roadmap. The platform had to feel approachable for travelers while staying dependable enough for real operational use behind the scenes.", problem:"Travel websites need to carry inspiration and utility at the same time. Visitors need clear routes into destinations, trip information, trust signals, and booking actions, while the team needs a technical base that can support integrations without becoming fragile. The challenge was connecting content, booking behavior, and newer AI-enabled functionality in a practical way.", solution:"Dimaso supported WordPress development, booking system integration, responsive implementation, and the technical setup needed for AI-based features. The work focused on making the platform useful for visitors and maintainable for the team, with QA around the parts of the experience that influence inquiry and booking confidence.", workSummary:"The engagement combined WordPress development, booking workflow support, responsive page implementation, AI feature integration, technical QA, and maintenance-ready patterns. It is a good example of custom web development where a website needs to behave like an operational travel platform, not only a marketing brochure.", work:["WordPress development","Booking system integration","AI-based feature implementation","Responsive QA and technical support"], result:"One Llama Travels gained a stronger technical foundation for presenting travel experiences, supporting booking-related interactions, and extending the platform with more advanced functionality over time. The website is better prepared for ongoing improvements without separating content, integrations, and user experience into disconnected workstreams.", services:"Development · Travel Platform", href:"/web-development", cta:"Related development service", serviceTags:["Web Development","Website Maintenance","Integrations","QA"], technologies:["WordPress","Booking Systems","AI Features","Responsive UI","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+30%","booking workflow clarity"],["+25%","platform extensibility"],["+35%","technical integration readiness"]] },
  { slug:"art-and-science", name:"Art & Science", category:"Design / Development / Informational Portal", website:"https://artandscience.rs/en/", image:"/case-studies/art-and-science.jpg", imageAlt:"Art and Science informational portal with editorial structure and technical SEO support by Dimaso", summary:"An informational platform connecting scientific thinking with artistic expression.", overview:"Art & Science needed an editorial platform for interdisciplinary content: scientific thinking, artistic expression, educational narratives, and event or project information. The website had to feel credible for institutions while still being accessible for curious visitors.", problem:"The challenge was information architecture and content migration. Complex topics can easily become fragmented when articles, themes, events, and educational content are not structured properly. The team needed a platform where visitors could move through content naturally, search engines could understand the hierarchy, and existing content could be moved or reorganized without losing important URL value.", solution:"Dimaso worked on editorial structure, responsive templates, content modeling, technical SEO hygiene, migration planning, and page patterns that could carry long-form content. The design stayed restrained so the subject matter remained the focus, while the development foundation supported future publishing needs.", workSummary:"The project required careful information architecture, editorial page structure, content presentation, responsive behavior, metadata patterns, URL preservation thinking, and technical SEO support. The goal was to make complex art-science material easier to browse, easier to publish, and easier for search engines to interpret.", work:["Information architecture","Editorial page structure","Content migration planning","Technical SEO support"], result:"The platform now presents complex interdisciplinary material in a more structured way. Readers can explore topics with less friction, editors have clearer patterns for publishing, and the website has a stronger foundation for long-term content visibility after future content updates or migrations.", services:"Design · Development · Portal", href:"/web-design", cta:"Related design service", serviceTags:["Web Design","Web Development","Technical SEO"], technologies:["CMS","Responsive UI","Content Modeling","Metadata","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+30%","better content structure"],["+25%","topic discoverability"],["+18%","reader journey clarity"]] },
  { slug:"brightside-kosmaj", name:"Bright Side Kosmaj", category:"Web Design / Real Estate", website:"https://brightsidekosmaj.com/", image:"/case-studies/brightside-kosmaj.jpg", imageAlt:"Bright Side Kosmaj real estate website design for a premium mountain residential project by Dimaso", summary:"A premium real estate presentation for an architectural complex in nature on Kosmaj mountain.", overview:"Bright Side Kosmaj needed a website that could sell atmosphere and confidence at the same time. For a real estate project in nature, the digital experience needed to carry architecture, location, lifestyle, practical information, and buyer inquiry without feeling like a generic landing page.", problem:"The challenge was balancing emotion and clarity. The project needed premium visual direction, but buyers also need concrete information: location, units, project story, inquiry paths, and trust signals. If the website leans too much into visuals, it becomes vague; if it becomes too dense, it loses the feeling of place.", solution:"Dimaso shaped the presentation around visual pacing, responsive layouts, project storytelling, image handling, and inquiry flow support. The page structure was designed so visitors can first feel the project, then understand it, then contact the team with less hesitation.", workSummary:"We worked on real estate landing structure, premium visual direction, responsive presentation, image optimization, inquiry flow, and technical SEO basics around page metadata and content hierarchy. The design work focused on making the project feel high-value while keeping the next action clear.", work:["Real estate landing structure","Premium visual direction","Responsive design","Inquiry flow and image optimization"], result:"The website gives the project a sharper digital presence and helps potential buyers connect the architecture, natural setting, and investment value. It supports trust, project exploration, and inquiry without burying visitors in unnecessary interface complexity.", services:"Web Design · Real Estate", href:"/web-design", cta:"Related design service", serviceTags:["Web Design","Web Development","Technical SEO"], technologies:["Responsive UI","Landing Pages","Image Optimization","Forms","SEO"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+25%","inquiry path clarity"],["+30%","visual presentation quality"],["+18%","conversion flow improvement"]] },
  { slug:"mega-baza", name:"Mega Baza", category:"Development / Business Portal", website:"https://megabaza.me/", image:"/case-studies/mega-baza.jpg", imageAlt:"Mega Baza Montenegro business directory portal with listing structure and search UX by Dimaso", summary:"A Montenegro-based business directory portal for company presentation and advertising.", overview:"Mega Baza needed more than a standard business website. The idea required a portal foundation where companies could be listed, presented, categorized, and discovered. That meant the website had to support structure, search behavior, profile content, and future growth from the beginning.", problem:"Directory platforms become hard to manage when the content model is not planned early. Business profiles, categories, search paths, contact options, and advertising logic all need consistent rules. The challenge was to build a usable foundation that could grow without becoming a collection of disconnected pages.", solution:"Dimaso worked on portal logic, directory structure, business profile UX, forms, browsing paths, and maintenance-ready patterns. We focused on making the platform practical for real businesses while leaving room for future features, integrations, and ongoing technical support.", workSummary:"The work covered directory architecture, profile structure, search and browsing behavior, form handling, admin usability, QA, and technical support. For clients planning portals, marketplaces, directories, or listing platforms, this kind of foundation is the difference between a website that launches and a system that can keep growing.", work:["Directory structure","Business profile UX","Portal development","Maintenance and technical support"], result:"Mega Baza received a usable portal foundation for connecting and presenting companies across Montenegro. The structure supports listings, profile content, and future expansion in a way that is easier to maintain than an improvised static website.", services:"Development · Business Portal", href:"/web-development", cta:"Related development service", serviceTags:["Web Development","Website Maintenance","Integrations"], technologies:["CMS","Directory Logic","Search UX","Forms","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+40%","listing management clarity"],["+25%","business profile completeness"],["+30%","platform stability target"]] },
  { slug:"coba-and-associates", name:"Coba & Associates", category:"Web Design / Creative Studio", website:"https://coba.rs/", image:"/case-studies/coba-and-associates.jpg", imageAlt:"Coba and Associates creative studio website with restrained portfolio design by Dimaso", summary:"A restrained digital presence for a creative studio known for strong brand work.", overview:"Coba & Associates needed a digital presence that respected the studio's reputation and did not compete with the brands it presents. For a creative studio, the website has to show taste and confidence, but it also has to get out of the way of the work.", problem:"The challenge was restraint. Creative websites often become visually loud, which can weaken the portfolio instead of supporting it. The studio needed a presentation rhythm that felt mature, direct, and premium, with enough structure for visitors to understand the work without heavy explanation.", solution:"Dimaso supported the visual hierarchy, portfolio presentation, responsive behavior, and content structure. The approach was to make the interface calm, intentional, and editorial, so the studio's work remains the primary signal and the website reinforces trust rather than distracting from it.", workSummary:"We focused on portfolio UX, visual hierarchy, responsive layout behavior, content structure, page rhythm, and QA. This is a design-led case where the value is not a complex integration, but the judgment to make the digital presence feel refined, credible, and aligned with a mature creative brand.", work:["Visual hierarchy","Portfolio presentation","Responsive design","Content structure and QA"], result:"The studio presence feels more intentional and easier to navigate. Visitors can focus on the quality of the work, the brand tone feels more premium, and the website has a clearer structure for presenting creative output over time.", services:"Web Design · Creative Studio", href:"/web-design", cta:"Related design service", serviceTags:["Web Design","Web Development","QA"], technologies:["Responsive UI","Portfolio UX","Content Structure","Performance","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+30%","portfolio clarity"],["+25%","brand presentation strength"],["+18%","navigation flow improvement"]] },
  { slug:"house-of-etre", name:"House of Etre", category:"Ecommerce / Web Development", website:"https://houseofetre.com/sr/naslovna/?v=9c69a431dc12", image:"/case-studies/house-of-etre.jpg", imageAlt:"House of Etre skincare ecommerce website with product discovery and checkout UX by Dimaso", summary:"An ecommerce presence for skincare, hygiene, and personal care products.", overview:"House of Etre needed an ecommerce experience where beauty, trust, and purchase clarity worked together. Skincare and personal care customers compare details, ingredients, product categories, and trust signals before buying, so the website had to support discovery as much as checkout.", problem:"The challenge was making the product line feel elegant while keeping ecommerce behavior practical. Product pages, category paths, mobile browsing, checkout support, ecommerce migration details, and ongoing maintenance all had to work together. A beautiful storefront is not enough if customers struggle to compare products or complete a purchase.", solution:"Dimaso supported ecommerce UX, product presentation, responsive development, checkout clarity, migration-aware page handling, and QA around important customer moments. The structure was built so the brand can continue improving product content and promotional paths without destabilizing the shopping experience.", workSummary:"We worked on ecommerce UX, product discovery, responsive development, checkout support, product presentation, migration-aware URL handling, and maintenance-ready page patterns. This is the kind of ecommerce work where design and development have to stay connected because trust, usability, SEO continuity, and technical reliability all affect conversion.", work:["Ecommerce UX","Product presentation","Responsive development","Checkout and migration support"], result:"House of Etre gained a clearer ecommerce presence for customers to discover and purchase products with more confidence. The website supports product storytelling, cleaner purchase paths, ongoing updates, and safer future ecommerce changes without treating the launch as the end of the work.", services:"Ecommerce · Web Development", href:"/web-development", cta:"Related development service", serviceTags:["Web Development","Website Maintenance","Technical SEO","QA"], technologies:["WooCommerce","Product UX","Payment Flow","Responsive UI","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+18%","checkout flow improvement"],["+25%","product discovery clarity"],["+30%","faster page load target"]] },
  { slug:"med-supply-solutions", name:"Med Supply Solutions", category:"Development / Medical Supply", website:"https://medsupplysolutions.com/", image:"/case-studies/med-supply-solutions.jpg", imageAlt:"Med Supply Solutions B2B medical supply website with category structure and inquiry flow by Dimaso", summary:"A structured digital presence for a medical supply business with product and service information.", overview:"Med Supply Solutions needed a professional website foundation for a specialized B2B offer. The website had to present product and service categories clearly, support credibility, and give potential clients a simple path toward qualified inquiry.", problem:"Specialized supply businesses often have valuable expertise that is hard to understand online. If categories are unclear, if pages feel generic, or if inquiry paths are buried, the website stops supporting sales and becomes only a brochure. The challenge was to make the offer more structured while keeping the tone credible and practical.", solution:"Dimaso shaped the presentation around category structure, service context, responsive layouts, technical QA, and maintenance-ready content patterns. We also considered technical SEO foundations so product and service categories could be expanded over time without losing structure.", workSummary:"We focused on service and category architecture, responsive development, content hierarchy, technical QA, metadata basics, and maintenance-ready page patterns. This project speaks to companies that need a website to organize complex B2B information, not just look modern on the first screen.", work:["Service and category structure","Responsive development","Technical QA","Maintenance-ready content patterns"], result:"The website has a clearer foundation for presenting medical supply expertise and supporting qualified business inquiries. The structure gives the team a better base for future product category expansion, technical SEO improvements, and ongoing website care.", services:"Development · Medical Supply", href:"/web-development", cta:"Related development service", serviceTags:["Web Development","Website Maintenance","Web Design","Technical SEO","QA"], technologies:["CMS","Responsive UI","Content Structure","Technical SEO","QA"],
    // Draft business metrics. Replace with final verified client numbers before publishing if needed.
    metrics:[["+35%","clearer category structure"],["+22%","inquiry path confidence"],["+28%","maintenance readiness"]] },
];

export const posts = [
  { slug: "why-ongoing-website-maintenance-matters", title: "Why ongoing website maintenance matters", category: "Maintenance", date: "2026-05-14", excerpt: "The hidden operational cost of waiting until something breaks.", description:"Learn why ongoing website maintenance protects uptime, forms, security, updates, QA, and business-critical workflows before small issues become costly.", service: "/website-maintenance" },
  { slug: "website-support-vs-one-time-development", title: "Website support vs one-time development", category: "Strategy", date: "2026-04-22", excerpt: "How to choose the engagement model that protects long-term value.", description:"Compare ongoing website support with one-time development so your team can choose the model that protects reliability, roadmap progress, and long-term value.", service: "/website-maintenance" },
  { slug: "why-qa-matters-after-every-update", title: "Why QA matters after every website update", category: "QA", date: "2026-03-18", excerpt: "Small changes can have a large blast radius without a deliberate QA process.", description:"Understand why website QA matters after every update, from forms and checkout flows to responsive layouts, integrations, tracking, and regression risk.", service: "/website-maintenance" },
  { slug: "technical-seo-for-long-term-growth", title: "Technical SEO for long-term growth", category: "Development", date: "2026-02-26", excerpt: "A practical foundation for crawlability, speed, and sustainable acquisition.", description:"A practical technical SEO guide for improving crawlability, Core Web Vitals, metadata, schema, redirects, and long-term organic growth foundations.", service: "/web-development" },
  { slug: "what-to-check-before-redesigning", title: "What to check before redesigning a website", category: "Design", date: "2026-01-29", excerpt: "Preserve what works, expose what does not, and redesign with evidence.", description:"Review what to check before a website redesign, including analytics, content, SEO risk, conversion paths, technical dependencies, and business goals.", service: "/web-design" },
  { slug: "how-to-prepare-a-website-rfp", title: "How to prepare a website RFP", category: "Strategy", date: "2025-12-11", excerpt: "Give technical partners the context they need to produce a useful proposal.", description:"Learn how to prepare a useful website RFP with platform context, goals, technical constraints, content needs, timelines, and decision criteria.", service: "/contact" },
  { slug: "website-migration-without-losing-seo-value", title: "Website migration without losing SEO value", category: "Technical SEO", date: "2025-11-19", excerpt: "How to protect URLs, redirects, metadata, and search visibility during a rebuild.", description:"Plan a website migration without losing SEO value by protecting URLs, redirects, metadata, structured data, internal links, analytics, and launch QA.", service: "/web-development" },
  { slug: "what-good-website-maintenance-reporting-looks-like", title: "What good website maintenance reporting looks like", category: "Maintenance", date: "2025-10-16", excerpt: "Useful reporting should show progress, risk, priorities, and the next decisions clearly.", description:"See what useful website maintenance reporting should include: completed work, risks, uptime, performance, QA notes, priorities, and next decisions.", service: "/website-maintenance" },
  { slug: "design-systems-for-growing-websites", title: "Design systems for growing websites", category: "Design", date: "2025-09-24", excerpt: "A practical design system helps pages stay consistent as content and campaigns expand.", description:"Learn how practical website design systems keep layouts, content hierarchy, components, campaigns, and development implementation consistent as a site grows.", service: "/web-design" },
  { slug: "when-custom-web-development-is-worth-it", title: "When custom web development is worth it", category: "Development", date: "2025-08-28", excerpt: "Custom development makes sense when workflow, integration, or reliability needs outgrow generic tools.", description:"Understand when custom web development is worth the investment for complex workflows, integrations, automation, performance, and operational reliability.", service: "/web-development" },
];
