export type Testimonial = {
  name: string;
  person: string;
  role: string;
  category: string;
  url?: string;
  scope: string;
  quote: string;
  alt: string;
  image?: string;
  youtubeId?: string;
  initials?: string;
};

// Replace testimonial copy and photos with final client-approved assets before publishing if required.
export const testimonials: Testimonial[] = [
  {
    name: "DriveDownCars",
    person: "Mitch Scher",
    role: "Project Owner",
    category: "Development / Automotive Platform",
    image: "/testimonials/drivedown-cars.jpg",
    alt: "DriveDownCars automotive platform built with custom database and vehicle listing functionality by Dimaso",
    scope: "Automotive platform with custom database structure and tailored functionality for vehicle listings and management",
    quote: "They delivered a high-performance platform that handles our specific database needs perfectly. For custom automotive solutions and reliable technical strategy, they are our go-to partner.",
    initials: "DD",
  },
  {
    name: "Forever Living Shop",
    person: "Branislav Rajic",
    role: "Doctor of Medicine / CEO for the Balkan region of the US FLP company",
    category: "Development / Ecommerce Platform",
    url: "https://foreverliving.com/",
    youtubeId: "nH2YofYi58U",
    alt: "Forever Living client video testimonial about ecommerce development and reliable delivery by Dimaso",
    scope: "A short client video about delivery quality, reliability, and collaboration rhythm.",
    quote: "The collaboration was structured, practical, and focused on making the platform easier to manage and more dependable for the team.",
    initials: "FLP",
  },
  {
    name: "Boots & Ladders",
    person: "Omar Kharbat",
    role: "Founder",
    category: "Development / Directory Platform",
    url: "https://bootsandladders.com/",
    image: "/testimonials/boots-and-ladders.jpg",
    alt: "Boots and Ladders directory platform with listings, user management, and payment integrations by Dimaso",
    scope: "Directory listing platform for service providers, including custom integrations for listings, user management, and payment systems",
    quote: "Dimaso helped us build a structured and scalable directory platform with custom integrations for listings and payments. Their ability to adapt existing tools and extend them to fit our specific needs made a significant difference in the reliability and usability of the system.",
    initials: "BL",
  },
  {
    name: "Project feedback",
    person: "YouTube testimonial",
    role: "Client feedback",
    category: "Development / Delivery Support",
    url: "https://www.youtube.com/watch?v=kw_GCPlWRV0",
    youtubeId: "kw_GCPlWRV0",
    alt: "Client video testimonial about Dimaso project communication and technical delivery",
    scope: "Short-form client feedback about project communication, execution, and technical confidence.",
    quote: "Dimaso brought clarity to the process and kept the technical work moving with care, consistency, and useful communication.",
    initials: "YT",
  },
  {
    name: "One Llama Travels",
    person: "Noel Kenehan",
    role: "Lead, AI Center of Excellence, Google Cloud Partnerships",
    category: "Development / Travel Platform",
    url: "https://onellamatravels.com/",
    image: "/testimonials/one-llama-peru.jpg",
    alt: "One Llama Travels Peru travel platform with booking system and AI feature integration by Dimaso",
    scope: "WordPress development, booking system integration, and implementation of AI-based features",
    quote: "Dimaso demonstrated a strong ability to combine solid WordPress development with more advanced integrations, including booking systems and AI-driven functionality. Their approach was structured, reliable, and focused on delivering practical solutions that worked in real-world scenarios.",
    initials: "OL",
  },
  {
    name: "Shiva Shakti",
    person: "Shiva Shakti team",
    role: "Project team",
    category: "Design / Membership Platform",
    url: "https://shiva-shakti.rs/",
    image: "/testimonials/shiva-shakti-yoga.jpg",
    alt: "Shiva Shakti yoga membership platform with accounts, payments, blog, and content management by Dimaso",
    scope: "Platform including membership system, user accounts, payment processing for members, blog, and content management functionality",
    quote: "The team delivered a reliable platform that combines membership management, payments, and content in a clear and functional way. Their work allowed us to manage our community and services efficiently, with a system that is stable and easy to maintain.",
    initials: "SS",
  },
  {
    name: "Call the Waiter",
    person: "Mag. Hana Bugarinovic Nikolic",
    role: "Project Representative",
    category: "Development / Hospitality Application",
    url: "https://callthewaiter.rs/",
    image: "/testimonials/hana-bugarinovic-nikolic.jpg",
    alt: "Mag. Hana Bugarinovic Nikolic testimonial for Call the Waiter hospitality communication application",
    scope: "Call the Waiter is an application that allows hotel and restaurant guests to call staff through the app. It also helps internal operations and communication between kitchen, service staff, and waiters.",
    quote: "Dimaso helped us present and support a digital product that improves the way hospitality teams communicate with guests and with each other. Their work gave the platform a clear, reliable, and professional digital presence.",
    initials: "CW",
  },
  {
    name: "Art & Science",
    person: "Dr. Eric Lale",
    role: "Director, Science Center",
    category: "Design / Development / Informational Portal",
    url: "https://artandscience.rs/en/",
    image: "/testimonials/eric-lale.jpg",
    alt: "Dr. Eric Lale testimonial for the Art and Science informational portal connecting science and art",
    scope: "Art & Science is a platform connecting art and science in Serbia. It presents interdisciplinary topics such as the influence of music on productive learning and neural activity.",
    quote: "Dimaso supported the creation of an informative digital platform that connects scientific thinking with artistic expression. The result is a clear, accessible, and structured website for presenting complex interdisciplinary topics.",
    initials: "AS",
  },
  {
    name: "Bright Side Kosmaj",
    person: "Tijana Kostic",
    role: "Architect / Lead Architect",
    category: "Web Design / Real Estate",
    url: "https://brightsidekosmaj.com/",
    image: "/testimonials/tijana-kostic.jpg",
    alt: "Tijana Kostic testimonial for Bright Side Kosmaj premium real estate website design",
    scope: "Bright Side Kosmaj presents a premium real estate complex in nature on Kosmaj mountain, developed with a strong architectural vision.",
    quote: "Dimaso helped present Bright Side Kosmaj through a polished digital experience that reflects the quality of the architecture, the natural setting, and the long-term value of the project.",
    initials: "BS",
  },
  {
    name: "Mega Baza",
    person: "Dejan Dujovic",
    role: "Director",
    category: "Development / Business Portal",
    url: "https://megabaza.me/",
    image: "/testimonials/dejan-dujovic.jpg",
    alt: "Dejan Dujovic testimonial for Mega Baza Montenegro business directory portal development",
    scope: "Mega Baza is a Montenegro-based business directory portal created to help companies in Montenegro advertise and present their businesses.",
    quote: "Dimaso helped us create the foundation for a business portal designed to connect companies across Montenegro. Their technical support and structured approach helped us move from idea to a usable digital platform.",
    initials: "MB",
  },
  {
    name: "Coba & Associates",
    person: "Slobodan Coba Jovanovic",
    role: "Founder / Creative Director",
    category: "Web Design / Creative Studio",
    url: "https://coba.rs/",
    image: "/testimonials/slobodan-coba-jovanovic.jpg",
    alt: "Slobodan Coba Jovanovic testimonial for Coba and Associates creative studio website design",
    scope: "Coba & Associates is a creative studio led by Slobodan Coba Jovanovic, known for creating some of the strongest brands in Serbia, Europe, and internationally.",
    quote: "Dimaso understood the importance of presenting a creative studio with clarity, restraint, and strong visual confidence. Their work helped us support a digital presence aligned with the quality of the brands we create.",
    initials: "CA",
  },
  {
    name: "House of Etre",
    person: "Alina Paipian",
    role: "Director",
    category: "Ecommerce / Web Development",
    url: "https://houseofetre.com/sr/naslovna/?v=9c69a431dc12",
    image: "/testimonials/alina-paipian.jpg",
    alt: "Alina Paipian testimonial for House of Etre skincare ecommerce website development",
    scope: "House of Etre is an ecommerce website for creams, skincare products, hygiene, and personal care products.",
    quote: "Dimaso helped us create and support an ecommerce presence that reflects the elegance and quality of the House of Etre product line. The website gives customers a clear and trustworthy way to discover and purchase our products.",
    initials: "HE",
  },
  {
    name: "Doctor Medica",
    person: "Ricky Montano",
    role: "Client / Project Representative",
    category: "Web Design / Website Development / Medical Website",
    url: "https://www.doctormedica.co/",
    image: "/testimonials/ricky-montano.jpg",
    alt: "Ricky Montano testimonial for Doctor Medica medical website design and development",
    scope: "Doctor Medica needed a clean, professional, and reliable website presence for a serious medical-facing brand.",
    quote: "Dimaso helped us create a clean, professional, and reliable website presence for Doctor Medica. Their work supported both the visual presentation and the technical structure needed for a serious medical-facing website.",
    initials: "DM",
  },
];
