import Link from "next/link";
import { Cases, FAQSection, ProcessStack, SectionHead, ServiceCards, TrustStrip } from "@/components/sections";
import { Testimonials } from "@/components/interactive-sections";
import { JsonLd } from "@/components/site";
import { TechVisual } from "@/components/tech-visual";
import { organizationId, organizationSchema, site, websiteId } from "@/lib/site";
import { homeFaq } from "@/content/data";
import { TrackedLink } from "@/components/tracked-link";

const featuredFaq=homeFaq.slice(0,4);

export default function Home(){return <main>
 <JsonLd data={{"@context":"https://schema.org","@graph":[organizationSchema,{"@type":"ProfessionalService","@id":`${site.url}/#professionalservice`,name:"Dimaso",url:site.url,email:site.email,telephone:site.phone,address:organizationSchema.address,areaServed:organizationSchema.areaServed,serviceType:["Website Maintenance","WordPress Maintenance and Support","Custom Web Development","Technical SEO Audits and Implementation","Web Design and Website Redesign","AI Website and Workflow Support","CMS Support","Hosting, Security, Backups","QA and Testing"],provider:{"@id":organizationId}},{"@type":"WebSite","@id":websiteId,url:`${site.url}/`,name:site.name,description:site.description,publisher:{"@id":organizationId}},{"@type":"FAQPage",mainEntity:featuredFaq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]}}/>
 <section className="grid-bg home-hero"><TechVisual/><span className="hero-plus p1">+</span><span className="hero-plus p2">+</span><span className="hero-plus p3">+</span><span className="hero-plus p4">+</span><div className="shell home-hero-copy"><span className="eyebrow">Senior website maintenance & development</span><h1>A senior web team that keeps your website reliable and moving forward.</h1><p className="lede">Monthly maintenance, custom development, web design, and technical SEO for organizations that need dependable technical ownership without building an internal web team.</p><div className="hero-actions"><TrackedLink tracking="cta" trackingLocation="home_hero" trackingLabel="Talk to a senior specialist" className="btn" href="#rfp">Talk to a senior specialist</TrackedLink><Link className="btn ghost" href="/case-studies">See client results</Link></div><p className="hero-assurance">Direct senior access · US & international collaboration · Project brief optional</p></div></section>
 <TrustStrip/>
 <section id="services" className="section home-section"><div className="shell"><SectionHead eyebrow="Three ways to work with us" title="Start with the problem the website needs to solve." copy="Bring us an active support backlog, a system that needs custom development, or a redesign that has to make the business easier to understand."/><div className="home-service-cards"><ServiceCards limit={3}/></div><Link href="/services" className="btn ghost" style={{marginTop:30}}>Explore all services</Link></div></section>
 <section className="section home-section home-work-section ambient-code ambient-right"><div className="shell"><SectionHead eyebrow="Selected work" title="Proof should make the decision easier." copy="These projects show the original context, the work Dimaso owned, and the practical change the website needed to support."/><div className="home-case-cards"><Cases limit={2}/></div><Link href="/case-studies" className="btn ghost" style={{marginTop:25}}>View all case studies</Link></div></section>
 <section className="section home-section ambient-code ambient-left"><div className="shell"><SectionHead eyebrow="Why Dimaso" title="Senior ownership stays close to the work." copy="The same people who understand the context help shape the solution, verify the release, and keep the next priority visible."/><div className="why-grid home-why-grid">{[["Direct senior access","You speak with the people designing, developing, testing, and improving the work."],["QA inside delivery","Critical pages, forms, checkout paths, and responsive states are verified as part of the work."],["Long-term context","We keep the website, business priorities, open risks, and next improvements connected over time."]].map(([title,copy],index)=><div className="card why-card" key={title}><span className="eyebrow">Commitment / 0{index+1}</span><h3>{title}</h3><p className="muted">{copy}</p></div>)}</div></div></section>
 <section className="section home-section ambient-code ambient-right"><div className="shell"><SectionHead eyebrow="Client perspective" title="Trust is built through delivery details." copy="Feedback from organizations that needed dependable development, website support, QA, and clear communication."/><div className="home-testimonials"><Testimonials/></div></div></section>
 <section className="section home-section ambient-code ambient-left"><div className="shell"><ProcessStack/></div></section>
 <FAQSection eyebrow="FAQ / Dimaso" title="Common questions before we start." copy="A concise overview of how Dimaso works, what we support, and how a new engagement begins." items={featuredFaq}/>
 </main>}
