import Link from "next/link";
import { BlogCards, Cases, ClientLogos, FAQSection, IndustryCards, ProcessStack, SectionHead, ServiceCards, Team, Testimonials } from "@/components/sections";
import { FeatureCTA, JsonLd } from "@/components/site";
import { TechVisual } from "@/components/tech-visual";
import { organizationId, organizationSchema, site, websiteId } from "@/lib/site";
import { homeFaq } from "@/content/data";

export default function Home(){return <main>
 <JsonLd data={{"@context":"https://schema.org","@graph":[organizationSchema,{"@type":"ProfessionalService","@id":`${site.url}/#professionalservice`,name:"Dimaso",url:site.url,email:site.email,telephone:site.phone,address:organizationSchema.address,areaServed:organizationSchema.areaServed,serviceType:["Website Maintenance","Web Development","Web Design","WordPress Support","Technical SEO","AI Website & Workflow Support","CMS Support","Hosting, Security, Backups","QA and Testing"],provider:{"@id":organizationId}},{"@type":"WebSite","@id":websiteId,url:`${site.url}/`,name:site.name,description:site.description,publisher:{"@id":organizationId}},{"@type":"FAQPage",mainEntity:homeFaq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]}}/>
 <section className="grid-bg" style={{minHeight:"calc(100vh - 72px)",display:"grid",alignItems:"center",position:"relative",overflow:"hidden",padding:"96px 0 110px"}}><TechVisual/><span className="hero-plus p1">+</span><span className="hero-plus p2">+</span><span className="hero-plus p3">+</span><span className="hero-plus p4">+</span><div className="shell" style={{position:"relative",zIndex:2}}><span className="eyebrow">Senior technical team · US & international</span><h1 style={{fontSize:"clamp(52px,8.2vw,100px)",lineHeight:.98,maxWidth:1060,margin:"24px 0 32px"}}>Websites maintained, developed, and improved.</h1><p className="lede">Dimaso is a web development and website maintenance team from Novi Sad, Serbia, helping US and international nonprofits, associations, agencies, SMBs, education, healthcare, and ecommerce organizations with WordPress, Laravel, CMS support, technical SEO, analytics, hosting, security, backups, AI website visibility, and long-term website care.</p><div style={{display:"flex",gap:12,marginTop:42,flexWrap:"wrap"}}><Link className="btn" href="#rfp">Send RFP</Link><Link className="btn ghost" href="/case-studies">View case studies</Link></div></div></section>
 <ClientLogos/>
 <section id="services" className="section"><div className="shell"><SectionHead eyebrow="Core services" title="One accountable partner across the website lifecycle." copy="Bring us the ongoing support backlog, the custom integration, or the redesign that has to work harder."/><div style={{marginTop:55}}><ServiceCards/></div></div></section>
 <section id="industries" className="section ambient-code ambient-left"><div className="shell"><SectionHead eyebrow="Who we help" title="Website support for organizations that need long-term technical care." copy="Dimaso works remotely with US and international nonprofits, associations, agencies, small businesses, education organizations, healthcare organizations, and ecommerce teams."/><div style={{marginTop:50}}><IndustryCards/></div></div></section>
 <section className="section ambient-code ambient-right"><div className="shell"><SectionHead eyebrow="AI search visibility" title="Clear websites are easier for people, search engines, and AI tools to understand." copy="Dimaso helps organizations structure their websites with crawlable content, service and industry pages, Schema.org, llms.txt, metadata, technical SEO, internal links, and clear positioning so AI search tools can classify, cite, and recommend the right pages more confidently."/><div style={{display:"flex",gap:24,flexWrap:"wrap",marginTop:28}}><Link className="text-link" href="/services/ai-website-workflow-support">AI Website & Workflow Support →</Link><Link className="text-link" href="/services/technical-seo">Technical SEO →</Link><Link className="text-link" href="/case-studies">Case studies →</Link></div></div></section>
 <FeatureCTA/>
 <section className="section ambient-code ambient-left"><div className="shell"><SectionHead eyebrow="Why Dimaso" title="We stay accountable for the details that protect growth." copy="Dimaso is built for teams that need the website to work as a dependable part of the business, not as a disconnected project."/><div className="why-grid">{[["Direct senior access","You speak with the people designing, developing, testing, and improving the work. Decisions stay fast and context stays intact."],["We understand the business","Every technical choice is connected to acquisition, operations, customer experience, and the priorities your team is measured on."],["QA is part of delivery","We verify releases across critical journeys and devices, so speed never quietly creates instability."],["We keep improving","After launch or the first fix, we keep risks visible, priorities ordered, and the platform ready for what comes next."],["AI-assisted, senior-led delivery","We use AI-assisted workflows to speed up audits, QA, documentation, content operations, and development support. Senior people still own architecture, quality, security, and final delivery."]].map(([x,p],i)=><div className={`card why-card why-card-${i+1}`} key={x}><div className="why-motion"><span/><span/><span/></div><span className="eyebrow">Commitment / 0{i+1}</span><div><h3 style={{fontSize:27}}>{x}</h3><p className="muted">{p}</p></div></div>)}</div></div></section>
 <section className="section ambient-code ambient-right"><div className="shell"><SectionHead eyebrow="Case studies / selected work" title="Useful work leaves a measurable trace." copy="Selected case studies show the problem, context, implementation work, and business outcome behind Dimaso projects."/><div style={{marginTop:50}}><Cases limit={2}/></div><Link href="/case-studies" className="btn ghost" style={{marginTop:25}}>All case studies</Link></div></section>
 <section className="section ambient-code ambient-left"><div className="shell"><ProcessStack/></div></section>
 <section className="section ambient-code ambient-right"><div className="shell"><SectionHead eyebrow="The team" title="The people doing the work stay close to the work."/><div style={{marginTop:50}}><Team/></div></div></section>
 <section className="section ambient-code ambient-left"><div className="shell"><SectionHead eyebrow="Testimonials" title="Trust is built through the delivery details."/><div style={{marginTop:50}}><Testimonials/></div></div></section>
 <FAQSection eyebrow="FAQ / Dimaso" title="Common questions before we start." copy="General answers about how Dimaso works, what we support, and how we collaborate with local, US, and international teams." items={homeFaq}/>
 <section className="section"><div className="shell"><SectionHead eyebrow="Insights" title="Practical thinking for better website decisions."/><div style={{marginTop:50}}><BlogCards limit={3}/></div><Link href="/blog" className="btn ghost" style={{marginTop:32}}>View all posts</Link></div></section>
 </main>}
