import Link from "next/link";
import { BlogCards, Cases, ClientLogos, FAQSection, ProcessStack, SectionHead, ServiceCards, Team, Testimonials } from "@/components/sections";
import { FeatureCTA, JsonLd } from "@/components/site";
import { TechVisual } from "@/components/tech-visual";
import { site } from "@/lib/site";
import { homeFaq } from "@/content/data";

export default function Home(){return <main>
 <JsonLd data={{"@context":"https://schema.org","@graph":[{"@type":"Organization",name:"Dimaso",url:site.url,email:site.email,telephone:site.phone,areaServed:["US","International"]},{"@type":"FAQPage",mainEntity:homeFaq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]}}/>
 <section className="grid-bg" style={{minHeight:"calc(100vh - 72px)",display:"grid",alignItems:"center",position:"relative",overflow:"hidden",padding:"96px 0 110px"}}><TechVisual/><span className="hero-plus p1">+</span><span className="hero-plus p2">+</span><span className="hero-plus p3">+</span><span className="hero-plus p4">+</span><div className="shell" style={{position:"relative",zIndex:2}}><span className="eyebrow">Senior technical team · US & international</span><h1 style={{fontSize:"clamp(52px,8.2vw,100px)",lineHeight:.98,maxWidth:1060,margin:"24px 0 32px"}}>Websites maintained, developed, and improved.</h1><p className="lede">Dimaso helps businesses keep their websites stable, fast, secure, and ready to grow through ongoing maintenance, custom development, design improvements, integrations, QA, and technical support.</p><div style={{display:"flex",gap:12,marginTop:42,flexWrap:"wrap"}}><Link className="btn" href="#rfp">Send us your RFP</Link><Link className="btn ghost" href="/case-studies">View case studies</Link></div></div></section>
 <ClientLogos/>
 <section id="services" className="section"><div className="shell"><SectionHead eyebrow="Core services" title="One accountable partner across the website lifecycle." copy="Bring us the ongoing support backlog, the custom integration, or the redesign that has to work harder."/><div style={{marginTop:55}}><ServiceCards/></div></div></section>
 <FeatureCTA/>
 <section className="section ambient-code ambient-left"><div className="shell"><SectionHead eyebrow="Why Dimaso" title="We stay accountable for the details that protect growth." copy="Dimaso is built for teams that need the website to work as a dependable part of the business, not as a disconnected project."/><div className="why-grid">{[["Direct senior access","You speak with the people designing, developing, testing, and improving the work. Decisions stay fast and context stays intact."],["We understand the business","Every technical choice is connected to acquisition, operations, customer experience, and the priorities your team is measured on."],["QA is part of delivery","We verify releases across critical journeys and devices, so speed never quietly creates instability."],["We keep improving","After launch or the first fix, we keep risks visible, priorities ordered, and the platform ready for what comes next."]].map(([x,p],i)=><div className={`card why-card why-card-${i+1}`} key={x}><div className="why-motion"><span/><span/><span/></div><span className="eyebrow">Commitment / 0{i+1}</span><div><h3 style={{fontSize:27}}>{x}</h3><p className="muted">{p}</p></div></div>)}</div></div></section>
 <section className="section ambient-code ambient-right"><div className="shell"><SectionHead eyebrow="Selected work" title="Useful work leaves a measurable trace."/><div style={{marginTop:50}}><Cases limit={2}/></div><Link href="/case-studies" className="btn ghost" style={{marginTop:25}}>All case studies</Link></div></section>
 <section className="section ambient-code ambient-left"><div className="shell"><ProcessStack/></div></section>
 <section className="section ambient-code ambient-right"><div className="shell"><SectionHead eyebrow="The team" title="The people doing the work stay close to the work."/><div style={{marginTop:50}}><Team/></div></div></section>
 <section className="section ambient-code ambient-left"><div className="shell"><SectionHead eyebrow="Testimonials" title="Trust is built through the delivery details."/><div style={{marginTop:50}}><Testimonials/></div></div></section>
 <FAQSection eyebrow="FAQ / Dimaso" title="Common questions before we start." copy="General answers about how Dimaso works, what we support, and how we collaborate with local, US, and international teams." items={homeFaq}/>
 <section className="section"><div className="shell"><SectionHead eyebrow="Insights" title="Practical thinking for better website decisions."/><div style={{marginTop:50}}><BlogCards limit={3}/></div><Link href="/blog" className="btn ghost" style={{marginTop:32}}>View all posts</Link></div></section>
 </main>}
