"use client";

/* eslint-disable @next/next/no-img-element -- external Simple Icons SVGs are lazy, tiny, and intentionally fetched from their CDN */

import { motion } from "framer-motion";
import { useRef, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { caseStudies, industries, posts, services } from "@/content/data";
import { testimonials } from "@/content/testimonials";

export function Reveal({children}:{children:React.ReactNode}) { return <motion.div initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.55}}>{children}</motion.div>; }
export function SectionHead({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <Reveal><span className="eyebrow">{eyebrow}</span><h2 style={{fontSize:"clamp(34px,4.6vw,60px)",maxWidth:850,margin:"16px 0 22px"}}>{title}</h2>{copy&&<p className="lede">{copy}</p>}</Reveal>}

export function ClientLogos(){
 const tech=[
  ["wordpress","WordPress"],["woocommerce","WooCommerce"],["nextdotjs","Next.js"],["react","React"],["typescript","TypeScript"],["nodedotjs","Node.js"],["php","PHP"],["mysql","MySQL"],["openapiinitiative","REST APIs"],["stripe","Stripe"],["googleanalytics","Google Analytics"],["googlesearchconsole","Google Search Console"],["figma","Figma"],["cloudflare","Cloudflare"]
 ];
 return <section className="client-strip"><div className="shell"><div className="client-strip-head"><span className="eyebrow">Technology stack</span><span className="client-note">Tools we use to maintain, build, measure, and improve websites</span></div></div><div className="client-logo-viewport"><div className="client-logo-track">{[...tech,...tech].map(([slug,name],i)=><div className="client-logo tech-logo" key={`${slug}-${i}`} title={name}><img src={`https://cdn.simpleicons.org/${slug}/57d99a`} alt={name} width="39" height="39" loading="lazy" decoding="async" fetchPriority="low"/><span>{name}</span></div>)}</div></div></section>;
}

export function ServiceCards(){
 const symbols=["↻","〈/〉","□","WP","SEO","AI"];
 return <div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:18}} className="cards-grid service-cards">{Object.values(services).map((s,i)=><Link href={`/${s.slug}`} key={s.slug} className={`service-card service-card-${(i%3)+1}`} style={{minHeight:500,display:"flex",flexDirection:"column",color:"#fff"}}><div className="service-graphic"><div className="service-signal"/><div className="service-symbol">{symbols[i]}</div></div><span className="eyebrow">0{i+1} / {s.eyebrow}</span><h3 style={{fontSize:29,margin:"30px 0 18px"}}>{s.label}</h3><p className="muted" style={{lineHeight:1.76}}>{s.intro}</p><span className="text-link" style={{marginTop:"auto"}}>Explore service →</span></Link>)}</div>
}

export function IndustryCards(){
 return <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14}} className="cards-grid industry-grid">{Object.values(industries).map((industry,index)=><Link key={industry.slug} href={`/${industry.slug}`} className="card" style={{color:"#fff",minHeight:220,display:"flex",flexDirection:"column"}}><span className="eyebrow">Industry / {String(index+1).padStart(2,"0")}</span><h3 style={{fontSize:24,margin:"22px 0 14px"}}>{industry.label}</h3><p className="muted" style={{lineHeight:1.65}}>{industry.who}</p><span className="text-link" style={{marginTop:"auto"}}>Explore industry →</span></Link>)}</div>;
}
export function Cases({limit,slugs}:{limit?:number;slugs?:string[]}){const studies=slugs?slugs.map(slug=>caseStudies.find(c=>c.slug===slug)).filter((c):c is (typeof caseStudies)[number]=>Boolean(c)):caseStudies;return <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:18}} className="cards-grid work-grid">{studies.slice(0,limit).map((c,i)=><article className="card case-card" key={c.name}><Link href={`/case-studies/${c.slug}`} className={`case-visual case-visual-${i+1}`} aria-label={`Read ${c.name} case study`}>{c.image&&<Image className="case-visual-image" src={c.image} alt={c.imageAlt} width={1200} height={700} sizes="(max-width: 900px) 100vw, 50vw" loading="lazy"/>}<span className="case-logo-mark">{c.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span className="case-logo-name">{c.name}</span><span className="case-visual-line one"/><span className="case-visual-line two"/></Link><div className="case-content"><div className="case-meta"><span className="tag">{c.category}</span><span>{c.services}</span></div><h3><Link href={`/case-studies/${c.slug}`}>{c.name}</Link></h3><p className="muted case-summary">{c.summary}</p><div className="case-links"><Link href={`/case-studies/${c.slug}`} className="text-link">View case study →</Link></div></div></article>)}</div>}
export function BlogCards({limit,page=1,perPage}:{limit?:number;page?:number;perPage?:number}){
 const start=perPage?(page-1)*perPage:0;
 const items=posts.slice(start,perPage?start+perPage:limit);
 return <div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:15}} className="cards-grid blog-grid">{items.map((p,i)=>{const number=start+i+1;return <Link href={`/blog/${p.slug}`} className="card blog-card" key={p.slug} style={{color:"#fff"}}><div className={`blog-card-visual blog-card-visual-${(number%6)||6}`}><span>{String(number).padStart(2,"0")}</span><i/><b/></div><span className="eyebrow">{p.category} · {new Date(p.date).toLocaleDateString("en-US",{month:"short",year:"numeric"})}</span><h3>{p.title}</h3><p className="muted">{p.excerpt}</p><span className="text-link">Read insight →</span></Link>})}</div>
}
export function Team(){
 const track=useRef<HTMLDivElement>(null);
 const drag=useRef({active:false,startX:0,scrollLeft:0});
 const [progress,setProgress]=useState(0);
 const [loaded,setLoaded]=useState<Record<string,boolean>>({});
 const team=[
  {name:"Predrag Stojanovic",role:"Web Design & WordPress Developer",image:"/team/predrag.webp",experience:"Active since 2008",bio:"Extensive experience in WordPress systems, platform architecture, and long-term maintenance. Focused on structuring scalable solutions, coordinating development efforts, and ensuring alignment between technical execution and platform needs."},
  {name:"Branislav Stojanovic",role:"Full Stack Developer",image:"/team/branislav.webp",experience:"Active since 2013",bio:"Strong experience in backend and frontend development, integrations, and system architecture. Responsible for implementing complex functionality, handling external integrations, and ensuring performance and reliability across the platform."},
  {name:"Sandra Lukic",role:"QA & Technical Support",image:"/team/sandra-lukic.webp",experience:"Active since 2011",bio:"Specializes in quality assurance, testing, and system validation. Responsible for ensuring stability, detecting issues before deployment, and maintaining consistent platform performance through structured testing processes."},
  {name:"Marko Milojevic",role:"Senior Web Developer",image:"/team/marko-milojevic.webp",experience:"Web development since 2016",bio:"Builds reliable frontend and backend features with a practical focus on performance, maintainability, and clean integrations. Marko helps turn complex requirements into stable website functionality that teams can keep improving."},
  {name:"Sanja Mazic",role:"Web QA & Project Support",image:"/team/sanja-mazic.webp",experience:"Quality-focused delivery",bio:"Keeps delivery organized across content, QA, and client feedback loops. Sanja supports releases with careful review, clear communication, and the kind of detail that helps projects feel calm from brief to launch."},
 ];
 const updateProgress=()=>{const node=track.current;if(!node)return;const max=node.scrollWidth-node.clientWidth;setProgress(max>0?node.scrollLeft/max:0)};
 const move=(direction:number)=>{const node=track.current;if(!node)return;const card=node.querySelector<HTMLElement>(".team-card");node.scrollBy({left:direction*((card?.offsetWidth||360)+16),behavior:"smooth"})};
 const onPointerDown=(event:React.PointerEvent<HTMLDivElement>)=>{const node=track.current;if(!node)return;drag.current={active:true,startX:event.clientX,scrollLeft:node.scrollLeft};node.setPointerCapture(event.pointerId);node.classList.add("is-grabbing")};
 const onPointerMove=(event:React.PointerEvent<HTMLDivElement>)=>{const node=track.current;if(!node||!drag.current.active)return;event.preventDefault();node.scrollLeft=drag.current.scrollLeft-(event.clientX-drag.current.startX);updateProgress()};
 const endDrag=(event:React.PointerEvent<HTMLDivElement>)=>{const node=track.current;if(!node)return;drag.current.active=false;node.classList.remove("is-grabbing");if(node.hasPointerCapture(event.pointerId))node.releasePointerCapture(event.pointerId)};
 return <div className="team-shell"><div className="team-head"><span className="client-note">Senior specialists · grab to scroll</span><div><button className="slider-control" onClick={()=>move(-1)} aria-label="Previous team members">←</button><button className="slider-control" onClick={()=>move(1)} aria-label="Next team members">→</button></div></div><div className="team-track" ref={track} onScroll={updateProgress} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={endDrag} onPointerCancel={endDrag}>{team.map(({name,role,image,experience,bio})=><article className="team-card" key={name}><div className={`image-preload-frame team-image-frame ${loaded[name]?"is-loaded":""}`}><Image src={image} alt={`${name}, ${role}`} width={500} height={520} sizes="(max-width: 900px) 86vw, 33vw" loading="lazy" onLoad={()=>setLoaded((current)=>({...current,[name]:true}))}/></div><div className="team-card-copy"><h3>{name}</h3><p className="team-role">{role}</p><p className="team-experience">{experience}</p><p className="muted">{bio}</p></div></article>)}</div><div className="team-progress" aria-hidden="true"><span style={{transform:`scaleX(${Math.max(.16,progress)})`}}/></div></div>
}
export function Testimonials(){
 const track=useRef<HTMLDivElement>(null);
 const [progress,setProgress]=useState(0);
 const [loaded,setLoaded]=useState<Record<string,boolean>>({});
 const updateProgress=()=>{const node=track.current;if(!node)return;const max=node.scrollWidth-node.clientWidth;setProgress(max>0?node.scrollLeft/max:0)};
 const move=(direction:number)=>{const node=track.current;if(!node)return;const max=node.scrollWidth-node.clientWidth;if(direction>0&&node.scrollLeft>=max-8){node.scrollTo({left:0,behavior:"smooth"});return}if(direction<0&&node.scrollLeft<=8){node.scrollTo({left:max,behavior:"smooth"});return}const card=node.querySelector<HTMLElement>(".testimonial-card");node.scrollBy({left:direction*((card?.offsetWidth||520)+20),behavior:"smooth"})};
 return <div className="testimonial-shell"><div className="testimonial-head"><span className="client-note">Client stories</span><div><button className="slider-control" onClick={()=>move(-1)} aria-label="Previous testimonials">←</button><button className="slider-control" onClick={()=>move(1)} aria-label="Next testimonials">→</button></div></div><div className="testimonial-track" ref={track} onScroll={updateProgress}>{testimonials.map((item,i)=><article className={`card testimonial-card ${item.youtubeId?"testimonial-video-card":""}`} key={`${item.name}-${i}`}><div className="testimonial-media">{item.youtubeId?<iframe src={`https://www.youtube-nocookie.com/embed/${item.youtubeId}`} title={item.alt} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/>:item.image?<div className={`image-preload-frame testimonial-image-frame ${loaded[item.name]?"is-loaded":""}`}><Image src={item.image} alt={item.alt} width={1200} height={700} sizes="(max-width: 900px) 88vw, 50vw" loading="lazy" onLoad={()=>setLoaded((current)=>({...current,[item.name]:true}))}/></div>:<div className="testimonial-site-shot"><div className="site-browser-bar"><span/><span/><span/></div><div className="site-shot-brand"><strong>{item.initials}</strong><span>{item.name}</span></div><div className="site-shot-lines"><span/><span/><span/></div><div className="site-shot-panel"/></div>}<div className="testimonial-signal"/><span className="eyebrow" style={{position:"absolute",left:18,bottom:15}}>Testimonial / {String(i+1).padStart(2,"0")}</span></div><div className="testimonial-copy"><span className="tag">Testimonial</span><h3>{item.name}</h3><p className="testimonial-category">{item.category}</p><p className="testimonial-scope">{item.scope}</p><blockquote>&ldquo;{item.quote}&rdquo;</blockquote><div className="testimonial-person"><span>{item.person}</span><small>{item.role}</small></div>{item.url&&<a className="text-link" href={item.url} target="_blank" rel="noopener noreferrer">Visit website →</a>}</div></article>)}</div><div className="testimonial-progress" aria-hidden="true"><span style={{transform:`scaleX(${Math.max(.12,progress)})`}}/></div></div>
}

export function ProcessStack({items=["Understand the context","Define priorities","Build and verify","Improve continuously"],title="Clear from first conversation to continuous improvement."}:{items?:readonly string[];title?:string}) {
 const motions=["audit","plan","build","improve"];
 const copy=["We map business priorities, technical constraints, risk, and the people who depend on the platform.","We turn context into an ordered roadmap with clear ownership, outcomes, and a practical delivery rhythm.","Senior specialists execute the work while QA stays inside every release, not after it.","We measure what changed, protect the system, and keep the next valuable improvement visible."];
 return <div className="process-layout"><div className="process-intro"><span className="eyebrow">How we work</span><h2 style={{fontSize:"clamp(36px,4vw,54px)",lineHeight:1.08,margin:"16px 0 20px"}}>{title}</h2><p className="lede" style={{fontSize:17}}>The process keeps context, delivery, quality, and continuous improvement connected.</p></div><div className="process-stack">{items.map((item,i)=><article className="process-step" key={item}><div className={`phase-motion ${motions[i]}`}><span/></div><div className="process-step-inner"><span className="eyebrow">Phase / 0{i+1}</span><div className="process-step-copy"><h3>{item}</h3><p className="muted">{copy[i]}</p></div></div></article>)}</div></div>
}

export function FAQSection({eyebrow,title,copy,items}:{eyebrow:string;title:string;copy:string;items:readonly (readonly [string,string])[]}) {
 const [openIndex,setOpenIndex]=useState(0);
 return <section className="section faq-section"><div className="shell faq-layout"><div className="faq-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p className="lede">{copy}</p></div><div className="faq-list">{items.map(([q,a],i)=><details className="faq-item" key={q} open={openIndex===i} onToggle={(event)=>{if(event.currentTarget.open)setOpenIndex(i)}}><summary onClick={(event)=>{event.preventDefault();setOpenIndex(i)}}><span className="faq-number">0{i+1}</span><span>{q}</span><span className="faq-toggle" aria-hidden="true"/></summary><div className="faq-answer"><p className="muted">{a}</p></div></details>)}</div></div></section>;
}
